FROM python:3.8-slim-buster

COPY install-packages.sh .
RUN ./install-packages.sh

COPY ./converter /app
WORKDIR /app
VOLUME /streams
VOLUME /shared
RUN pip install -r requirements.txt
CMD ["python", "-u", "./stream_converter.py"]